uint8 OUT = 1                # Player should leave the field
uint8 IN = 2                 # Player should enter the field
uint8 type                   # Must be IN or OUT
handball_msgs/Posture post   # Position to reach, when type is IN
---
uint8 SUCCESS = 0      
uint8 FAILURE = 1
uint8 status                 # Final status of the action
---
uint8 percent
